# SPDX-FileCopyrightText: 2020 - 2021 Intel
# SPDX-FileCopyrightText: 2020 - 2021 Fraunhofer SIT sponsored by Infineon
# SPDX-FileCopyrightText: 2021 - 2022 Infineon Technologies AG
# SPDX-FileCopyrightText: 2023 - 2024 Juergen Repp
# SPDX-License-Identifier: BSD-2-Clause

task:
  env:
    CFLAGS: "-I/usr/local/include -I/usr/local/openssl/include"
    LDFLAGS: -L/usr/local/lib
    libusb_version: v1.0.26
  freebsd_instance:
    matrix:
      image_family: freebsd-14-3
  install_script:
    - IGNORE_OSVERSION=yes
    - pkg update -f
    - pkg upgrade -y
    - pkg install -y bash gmake coreutils libtool pkgconf autoconf autoconf-archive
    - pkg install -y automake openssl json-c cmocka uthash wget curl git util-linux
    - pkg install -y libftdi1
    - pkg install -y swtpm
    - git clone --depth 1 -b $libusb_version https://github.com/libusb/libusb
    - cd libusb && ./bootstrap.sh && ./configure && gmake -j install
    - cd - && rm -fr libusb
  script:
    #
    # Due to a race condition that only occurs in the cirrus ci, "make distcheck" has been replaced by "make check".
    #
    ./bootstrap &&
    ./configure --enable-self-generated-certificate --enable-unit=yes --enable-integration=yes --with-crypto=ossl --disable-doxygen-doc --enable-tcti-swtpm=yes --enable-tcti-libtpms=no --enable-tcti-mssim=no --disable-dependency-tracking &&
    gmake -j check || { cat /tmp/cirrus-ci-build/tpm2-tss-*/_build/sub/test-suite.log; exit 1; }
