# SPDX-FileCopyrightText: 2019 Fraunhofer SIT sponsored by Infineon
# SPDX-License-Identifier: BSD-2-Clause

ignore:
  - "test"

coverage:
  status:
    project:
      default:
        threshold: 1%

comment:
  behavior: new
