#! /bin/sh

# generate list of source files for use in Makefile.am
# if you add new source files, you must run ./bootstrap again
function src_listvar () {
    basedir=$1
    suffix=$2
    var=$3

    find "${basedir}" -name "${suffix}" | tr '\n' ' ' | (echo -n "${var} = " && cat)
    echo ""
}

VARS_FILE=src_vars.mk

echo "Generating file lists: ${VARS_FILE}"
if [ -e ${VARS_FILE} ]; then rm ${VARS_FILE}; fi

src_listvar "sysapi/include" "*.h" "SYSAPI_H" >> ${VARS_FILE}
src_listvar "sysapi/sysapi" "*.c" "SYSAPI_C" >> ${VARS_FILE}
src_listvar "sysapi/sysapi_util" "*.c" "SYSAPIUTIL_C" >> ${VARS_FILE}
echo -e "SYSAPI_SRC = \$(SYSAPI_H) \$(SYSAPI_C) \$(SYSAPIUTIL_C)\n" >> ${VARS_FILE}

src_listvar "common" "*.c" "COMMON_C" >> ${VARS_FILE}
src_listvar "common" "*.h" "COMMON_H" >> ${VARS_FILE}
echo -e "COMMON_SRC = \$(COMMON_C) \$(COMMON_H)\n" >> ${VARS_FILE}

src_listvar "tcti/localtpm" "*.c" "LOCALTPM_C" >> ${VARS_FILE}
src_listvar "tcti/localtpm" "*.h" "LOCALTPM_H" >> ${VARS_FILE}
echo -e "LOCALTPM_SRC = \$(LOCALTPM_C) \$(LOCALTPM_H)\n" >> ${VARS_FILE}

src_listvar "test/common/sample" "*.c" "SAMPLE_C" >> ${VARS_FILE}
src_listvar "test/common/sample" "*.h" "SAMPLE_H" >> ${VARS_FILE}
echo -e "SAMPLE_SRC = \$(SAMPLE_C) \$(SAMPLE_H)\n" >> ${VARS_FILE}

src_listvar "tcti/tpmsockets" "*.cpp" "TPMSOCKETS_C" >> ${VARS_FILE}
src_listvar "tcti/tpmsockets" "*.h" "TPMSOCKETS_H" >> ${VARS_FILE}
echo -e "TPMSOCKETS_SRC = \$(TPMSOCKETS_C) \$(TPMSOCKETS_H)\n" >> ${VARS_FILE}

libtoolize --install \
&& aclocal \
&& autoconf \
&& automake --add-missing
