#;**********************************************************************;
#
# Copyright (c) 2015, Intel Corporation
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without 
# modification, are permitted provided that the following conditions are met:
# 
# 1. Redistributions of source code must retain the above copyright notice, 
# this list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright notice, 
# this list of conditions and the following disclaimer in the documentation 
# and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF 
# THE POSSIBILITY OF SUCH DAMAGE.
#;**********************************************************************;

RESOURCE_MGR_OBJS := $(shell ls ../resourcemgr/*.c | sed 's/..\/resourcemgr/$(TARGET_TYPE)/' | sed 's/.c$$/.o /' )
RESOURCE_MGR_HEADERS := $(shell ls ../resourcemgr/*.h )
SAMPLE_OBJS := $(shell ls sample/*.c | sed 's/sample/$(TARGET_TYPE)/' | sed 's/.c$$/.o /' )
SAMPLE_HEADERS := $(shell ls sample/*.h )
TPMSOCKETS_OBJS := $(shell ls ../tpmsockets/*.cpp | sed 's/..\/tpmsockets/$(TARGET_TYPE)/' | sed 's/.cpp$$/.o /' )
TPMSOCKETS_HEADERS := $(shell ls ../tpmsockets/*.h )
SYSCONTEXT_OBJS := $(shell ls ../syscontext/*.c | sed 's/..\/syscontext/$(TARGET_TYPE)/' | sed 's/.c$$/.o /' )
SYSCONTEXT_HEADERS := $(shell ls ../syscontext/*.h )

TPMCLIENT_HEADERS = tpmclient.h $(SAMPLE_HEADERS) $(TPMSOCKETS_HEADERS)


CC = gcc
CPLUS = g++

debug_CFLAGS = -O0 -ggdb3 -Wall -Werror
release_CFLAGS = -Os -Wall -Werror
debug_CPLUSFLAGS = -O0 -ggdb3 -fno-operator-names -fpermissive -Wall -Werror
release_CPLUSFLAGS = -Os -fno-operator-names -fpermissive -Wall -Werror

CFLAGS = $($(TARGET_TYPE)_CFLAGS)
CPLUSFLAGS = $($(TARGET_TYPE)_CPLUSFLAGS)

INCLUDES = -I../../include -I../.. -I. $(INCLUDE_DIRS) -I../tpmsockets -I../syscontext -Isample -I../resourcemgr
RESMGR_INCLUDES = $(INCLUDES) -I../resourcemgr.h
LIBS = ../../lib/$(TARGET_TYPE)/libtpm.a

OBJS = $(SYSCONTEXT_OBJS)

.PHONY: tpmlib_debug tpmlib_release DIRS all debug release 

all:  debug release 

debug: tpmlib_debug
	$(MAKE) -f makefile.linux debug/tpmclient TARGET_TYPE=debug
	$(MAKE) -f makefile.linux debug/resourcemgr TARGET_TYPE=debug

release: tpmlib_release
	$(MAKE) -f makefile.linux release/tpmclient TARGET_TYPE=release
	$(MAKE) -f makefile.linux release/resourcemgr TARGET_TYPE=release

DIRS:
	-@mkdir $(TARGET_TYPE) 2> /dev/null

tpmlib_debug: 
	@$(MAKE) -C ../.. -f makefile.linux debug

tpmlib_release: 
	@$(MAKE) -C ../.. -f makefile.linux release

$(TARGET_TYPE)/tpmclient: DIRS $(TARGET_TYPE)/tpmclient.o $(OBJS) $(SAMPLE_OBJS) $(LIBS) makefile.linux $(TARGET_TYPE)/sapiclient_tpmsockets.o
	$(CPLUS) $(CPLUSFLAGS) $(INCLUDES) -o $(@D)/tpmclient $(@D)/tpmclient.o $(@D)/sapiclient_tpmsockets.o $(OBJS) $(SAMPLE_OBJS) $(LIBS)

$(TARGET_TYPE)/resourcemgr: $(TARGET_TYPE)/resourcemgr.o $(OBJS) $(TPMSOCKETS_OBJS) $(LIBS) makefile.linux 
	$(CPLUS) $(CPLUSFLAGS) $(RESMGR_INCLUDES) -pthread -o $(TARGET_TYPE)/resourcemgr $(RESOURCE_MGR_OBJS) $(TPMSOCKETS_OBJS) $(OBJS) $(LIBS)

$(TARGET_TYPE)/%.o: %.cpp $(TPMCLIENT_HEADERS) makefile.linux
	$(CPLUS) $(CFLAGS) $(INCLUDES) -c $< -o $@

$(TARGET_TYPE)/%.o: ../resourcemgr/%.c $(RESOURCE_MGR_HEADERS) makefile.linux
	$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@

$(TARGET_TYPE)/%.o: sample/%.c $(SAMPLE_HEADERS) makefile.linux
	$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@

$(TARGET_TYPE)/%.o: ../tpmsockets/%.cpp $(TPMSOCKETS_HEADERS) makefile.linux
	$(CPLUS) $(CPLUSFLAGS) $(INCLUDES) -c $< -o $@

# Build special version of tpmsockets code for test application.
$(TARGET_TYPE)/sapiclient_tpmsockets.o: ../tpmsockets/tpmsockets.cpp	$(TPMSOCKETS_HEADERS) makefile.linux
	$(CPLUS) -DSAPI_CLIENT $(CPLUSFLAGS) $(INCLUDES) -c $< -o $@

$(TARGET_TYPE)/%.o: ../syscontext/%.c	$(SYSCONTEXT_HEADERS) makefile.linux
	$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@

clean:
	@rm -f tpmclient resourcemgr 
	@rm debug -rf
	@rm release -rf
	@$(MAKE) -C ../.. -f makefile.linux clean