# SPDX-FileCopyrightText: 2026 Juergen Repp
# SPDX-License-Identifier: BSD-2-Clause

name: FreeBSD CI

on:
  [push, pull_request]

jobs:
  freebsd-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Test in FreeBSD
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          prepare: |
            export ASSUME_ALWAYS_YES=yes
            export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig"
            export PATH="/usr/local/bin:/usr/local/sbin:$PATH"
            rm -rf /var/db/pkg/repo-* /var/db/pkg/FreeBSD.meta /var/cache/pkg/*
            pkg bootstrap -f
            pkg update -f
            pkg install -y autoconf autoconf-archive automake bash cmocka \
              coreutils curl doxygen git gmake json-c libftdi1 libtool \
              libtpms libuuid openssl pkgconf swtpm uthash wget
            pkg update -f
            sync

          run: |
            export PATH="/usr/local/bin:/usr/local/sbin:$PATH"
            cd /home/runner/work/tpm2-tss/tpm2-tss
            export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig"
            export CFLAGS="-I/usr/local/include -I/usr/local/openssl/include"
            export LDFLAGS="-L/usr/local/lib"
            export LIBUSB_LIBS="-lusb"
            export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig"
            git config --global --add safe.directory /home/runner/work/tpm2-tss/tpm2-tss
            ./bootstrap
            ./configure --disable-dependency-tracking \
                        --enable-integration \
                        --enable-self-generated-certificate \
                        --enable-tcti-libtpms \
                        --enable-tcti-mssim \
                        --enable-tcti-spi-ltt2go \
                        --enable-tcti-swtpm \
                        --enable-unit \
                        --with-crypto=ossl
            gmake -j check || {
              find . -name test-suite.log -exec sh -c \
                'echo "===== $1 ====="; cat "$1"' sh {} \;
              exit 1
            }
